language: python
python:
- '3.4'
- '3.5'
install:
- pip install .
script: py.test
notifications:
  irc:
    channels:
    - irc.freenode.net#ideascube
    on_success: change
    on_failure: always
  email: false
